name: CI

on: 
  push:
    paths:
      - '!.github/**'
      - '!*.md'
      - '!LICENSE'

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild clean test -project Timesheets.xcodeproj -scheme Timesheets -destination "platform=iOS Simulator,name=iPhone 8" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
